name: Migration Check

on:
  pull_request:
    paths:
      - 'migrations/**'
    types: [opened, synchronize, reopened]

jobs:
  check-migrations:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Atlas
        uses: ariga/setup-atlas@v0
      
      - name: Lint Migrations
        run: atlas migrate lint --dev-url "docker://postgres/17/test" --git-base "origin/main"
