name: Migration Check

on:
  pull_request:
    paths:
      - 'migrations/**'
    types: [opened, synchronize, reopened]

jobs:
  check-migrations:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Atlas
        uses: ariga/setup-atlas@4240bd74ba9f13319a21de2b6e497f2b6d184d76 # v0
      
      - name: Lint Migrations
        run: atlas migrate lint --dev-url "docker://postgres/17/test" --git-base "origin/main"
